flair/flair/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('', include('home.urls', namespace="home")),
    path('admin/', admin.site.urls),
]

flair/home/urls.py
from django.urls import path
from .views import home, calculate_readability

urlpatterns = [
    path('', home, name='home'),
    path('calculate-readability/', calculate_readability, name='calculate_readability'),
]

app_name = "home"

flair/home/models.py
from django.db import models

# Create your models here.

flair/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .feature_extractor import *
from .flair_model import *

def home(request):
    # Remove images from the static folder
    try:
        image_path = os.path.join(os.getcwd(), 'static', 'wordcloud.png')
        if os.path.exists(image_path):
            os.remove(image_path)
    except Exception as e:
        # Handle any exceptions, such as permission errors
        print(f"Error removing image: {e}")
    
    #Check if images are in the static folder
    wordcloud_exists = os.path.exists(os.path.join(os.getcwd(), 'static', 'wordcloud.png'))
    embeddings_exists = os.path.exists(os.path.join(os.getcwd(), 'static', 'word_embeddings.png'))
    
    
    return render(request, 'home.html', {
        # Your existing context data...
        'wordcloud_exists': wordcloud_exists,
        'embeddings_exists': embeddings_exists
    })

def calculate_readability(request):
   if request.method == 'POST':
        # Check if the text was provided
        text = request.POST.get('text-input', '')
        embeddings = request.POST.get('embed-input', '')
        
        # Save the text input to the session
        request.session['text_input'] = text
        request.session['embed_input'] = embeddings

        # Check if a file was uploaded
        file = request.FILES.get('file-input')

        if text or file:
            if text:
                # If text is provided, use it
                data = text
            else:
                # If file is uploaded, read its contents
                data = file.read().decode('utf-8')

            features = extract(data)
            prediction = get_pred(*features)
            wordcloud_path = create_wordcloud(data)
            word_embeddings = wordembed(embeddings)
    
            
            #Check if images are in the static folder
            wordcloud_exists = os.path.exists(os.path.join(os.getcwd(), 'static', 'wordcloud.png'))
           
            return render(request, 'home.html', {
                'text_input': text,
                'word_count': features[0],
                'sentence_count': features[1],
                'ave_word': features[2],
                'ave_sent': features[3],
                'total_syll': features[4],
                'min_prediction': prediction[0][0],
                'max_prediction': prediction[0][1],
                'wordcloud': wordcloud_path,
                'embeddings': word_embeddings,
                
                'wordcloud_exists': wordcloud_exists
            })
    
        return HttpResponse("No input provided")

def extract(text):
    cleaned_text = text.strip().lower()
    
    wordcount = word_count(cleaned_text)
    sentcount = sentence_count(cleaned_text)
    avewordlength = avg_word_length(cleaned_text)
    avesentlength = avg_sent_length(cleaned_text)
    totalsyll, monosyll, polysyll = count_syllables(cleaned_text)
    
    word_tokens, tagged_text = tag_text(cleaned_text)
    NTR = ntr(word_tokens, tagged_text)
    VTR = vtr(word_tokens, tagged_text)
    TTR, root_ttr, corr_ttr, bilog_ttr = ttr(word_tokens, tagged_text)
    lexdensity = lexical_density(word_tokens, tagged_text)
    FWTR = fwtr(word_tokens, tagged_text)
    
    return wordcount, sentcount, avewordlength, avesentlength, totalsyll, monosyll, polysyll, NTR, VTR, TTR, root_ttr, corr_ttr, bilog_ttr, lexdensity, FWTR

def get_pred(wordcount, sentcount, avewordlength, avesentlength, totalsyll, monosyll, polysyll, ntr, vtr, ttr, root_ttr, corr_ttr, bilog_ttr, lexdensity, fwtr):
    import pickle

    try:
        with open("flair_model.sav", "rb") as model_file:
            model = pickle.load(model_file)
    except FileNotFoundError:
        return "Model file not found"
    except EOFError:
        return "Model file is empty or corrupted"

    try:
        with open("scaler.sav", "rb") as scaler_file:
            scaled = pickle.load(scaler_file)
    except FileNotFoundError:
        return "Scaler file not found"
    except EOFError:
        return "Scaler file is empty or corrupted"

    try:
        prediction = model.predict(scaled.transform([[wordcount, sentcount, avewordlength, avesentlength, totalsyll, monosyll, polysyll, ntr, vtr, ttr, root_ttr, corr_ttr, bilog_ttr, lexdensity, fwtr]]))
        return prediction
    except Exception as e:
        return f"Error occurred during prediction: {str(e)}"
    
def create_wordcloud(text):
    word_freq(text)
    wordcloud_path = os.getcwd() + "/static/wordcloud.png"
    return wordcloud_path

flair/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link href=" {% static '/css/home.css' %} " rel="stylesheet" type="text/css"/>
        <title>FLAIR</title>
    </head>
    <body>
        <div class="main">
            <div class="title">
                <h1>FLAIR</h1>
                <h4>Filipino Language AI Readability Tool</h4>
            </div>

            <div class="main-containers">
                <div class="left-container">
                    <h2>Assess the readability of your texts</h2>
                    <p>Enter your text or upload your text file below to calculate its readability level. Minimum input must be one (1) paragraph.</p>
                    <form id="flair-form" method="post" action="{% url 'home:calculate_readability' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <textarea id="text-input" name="text-input" placeholder="Input your text here...">{{ text_input }}</textarea>
                        <p>OR</p>
                        <div class="file-upload">
                            <input type="file" id="file-input" name="file-input" accept=".doc, .docx, .txt">
                        </div>
                        <br><p>Input a word to discover associated words:</p>
                        <textarea id="embed-input" name="embed-input" placeholder="Input your text here...">{{ embed_input }}</textarea>
                        <div class="bottom-container">
                            <input type="submit" value="CALCULATE READABILITY" id="submit">
                            <div class="results-container">
                                <h3>READABILITY RESULTS:</h3>
                                <p><b>Recommended Age Range: </b> <span class="age-range"></span>{{min_prediction}}-{{max_prediction}}</p>
                                <div class="tabs">
                                    <input type="radio" class="tab-button" id="basic-features" name="text-features" value="0" onclick="showResults()" checked><label class="label" for="basic-features">Basic Text Features</label>
                                    <input type="radio" class="tab-button" id="advanced-features" name="text-features" value="1" onclick="showResults()"><label class="label" for="advanced-features">Advanced Text Features</label>
                                </div>
                                <div class="results" id="basic-results">
                                    <ul>
                                        <li>Word Count: <span id="word-count"></span>{{word_count}}</li>
                                        <li>Sentence Count: <span id="sent-count"></span>{{sentence_count}}</li>
                                        <li>Average Word Length: <span id="ave-word"></span>{{ave_word}}</li>
                                        <li>Average Sentence Length: <span id="ave-sent"></span>{{ave_sent}}</li>
                                        <li>Total Number of Syllables: <span id="total-syll"></span>{{total_syll}}</li>
                                    </ul>
                                </div>
                                <div class="results" id="advanced-results">
                                    <ul>
                                        <li> Word Frequencies:
                                        {% if wordcloud_exists %}
                                            <li> <img src="{% static 'wordcloud.png' %}" alt="Word Cloud" id="word-freq" width="400px">
                                        {% endif %}
                                        <li>Related Words from Word Embeddings:
                                            <li><span id="word-em"></span>{{embeddings}}
                                        
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="right-container">
                    <h3>What is FLAIR?</h3>
                    <p>FLAIR is an AI Tool that uses machine learning to assess the readability level of Filipino texts, particularly for Filipino children’s literature. </p>
                </div>
            </div>
        </div>

        <script>
            function showResults() {
                var value = document.querySelector('input[name="text-features"]:checked').value;
                if (value === "0") {
                    document.getElementById("basic-results").style.display = 'block';
                    document.getElementById("advanced-results").style.display = 'none';
                } else if (value === "1") {
                    document.getElementById("basic-results").style.display = "none";
                    document.getElementById("advanced-results").style.display = 'block';
                }
            }  

            function submitForm() {
                var form = document.getElementById("flair-form");
                var formData = new FormData(form);
                var xhr = new XMLHttpRequest();
                
                xhr.onreadystatechange = function() {
                    if (xhr.readyState === XMLHttpRequest.DONE) {
                        if (xhr.status === 200) {
                            document.getElementById("results-container").innerHTML = xhr.responseText;
                        } else {
                            console.error('Request failed:', xhr.status);
                        }
                    }
                };
                
                xhr.open("POST", form.action);
                xhr.send(formData);
            }
        </script>
    </body>
</html>